services:
  - type: web
    name: seaseeai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn simple_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
  # Note: Python version is specified via the PYTHON_VERSION env var and runtime.txt
    healthCheckPath: /health