global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'seaseeai-api'
    static_configs:
      - targets: ['seaseeai-api:8000']
    metrics_path: '/metrics'
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
